export enum Config {
  baseUrl = 'http://185.185.71.244:81/ducks/',
  loginUrl = 'auth/login',
  registerUrl = 'register/new',
  ducksUrl = 'ducks/users/all',
  duckUrl = 'ducks/details/',
  duckAddUrl = 'ducks/new',
  duckUpdateUrl = 'ducks/update/',
  duckDeleteUrl = 'ducks/delete/',
  ducksAccessibleUrl = 'ducks/accessible',
  userEventsUrl = 'events/users/all',
  eventAddUrl = 'events/new',
  eventUrl = 'events/details/',
  userUrl = 'users/me',
  eventsUrl = 'events/upcoming',
  userUpdateUrl = 'users/update/',
  userRequestsUrl = 'requests/users/all',
  requestAddUrl = 'requests/new/',
  requestUrl = 'requests/details/',
  eventRegisterUrl = 'events/register/'
}
